replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: 336151728602.dkr.ecr.us-east-1.amazonaws.com/ctrlr
  tag: REPLACE_WITH_IMAGE_TAG
service:
  name: ctrlr
  type: LoadBalancer
  externalPort: 80
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: false
