{{- if .Values.rollout }}
apiVersion: argoproj.io/v1alpha1               # Create a rollout resource
kind: Rollout
{{- else }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
{{- if .Values.rollout }}
  strategy:
{{ toYaml .Values.rollout.strategy | indent 4 }}
{{- end }}
  template:
    metadata:
      annotations:
        buildID: "{{ .Values.buildID }}"
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 12 }}