name: Docker Image CI

on: [ push, pull_request ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building the Docker image
      run: docker build . --file Dockerfile --tag color-service:${{ github.sha }}

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.5.1
      with:
        image: color-service
        tags: ${{ github.sha }}
        registry: quay.io
        username: codefresh_sa
        password: ${{ secrets.docker_registry_password }}
