name: Docker Image CI

on:
  push:
    branches:
      - main
    paths:
      - color/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Create SHORT_SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      
    - name: Building the Docker image
      run: |
        cd color;
        docker build . --tag codefresh_sa/color-service:${{ steps.vars.outputs.sha_short }}

    - name: Push To Registry
      uses: redhat-actions/push-to-registry@v2.5.1
      with:
        image: codefresh_sa/color-service
        tags: ${{ steps.vars.outputs.sha_short }}
        registry: quay.io
        username: codefresh_sa+csdp_salesdemo_dev
        password: ${{ secrets.docker_registry_password }}

  csdp-report-image-info:
  
    runs-on: ubuntu-latest
    
    needs: [build]
  
    container:
      image: quay.io/codefreshplugins/argo-hub-workflows-codefresh-csdp-versions-0.0.6-images-report-image-info:main
    
    steps:
      - name: Report Docker Image to CSDP
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            export "GIT_BRANCH=${{ github.head_ref }}"
          else
            export "GIT_BRANCH=${{ github.ref_name }}"
          fi
          node /usr/src/app/index.js
        working-directory: /usr/src/app
        env:
          IMAGE_URI: quay.io/codefresh_sa/color-service:${{ steps.vars.outputs.sha_short }}
          CF_API_KEY: ${{ secrets.CF_RUNTIME_KEY }}
          GIT_BRANCH: ${{ github.ref_name }}
          GIT_REVISION: ${{ github.sha }}
          GIT_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GIT_COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
          DOCKER_USERNAME : codefresh_sa+csdp_salesdemo_dev
          DOCKER_PASSWORD : ${{ secrets.docker_registry_password }}
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{github.workflow}}
          LOGS_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GIT_SENDER_LOGIN: ${{ github.actor }}
          CF_HOST: https://g.codefresh.io
